# declares a normal variable, so at definition it runs the rhs and does the binding to the name
random_names := rname1 rname2 rname3

#.DEFAULT_GOAL := test2

test:
	echo "--- running test make target --- \n"
	echo "-- printing MAKE variable:" $(MAKE) "\n"
	echo "-- printing COQBIN variable:" $(COQBIN) "\n"
	echo $(random_names) "\n"

test2:
	echo "test2"

# .PHONY