# wandb-sweep-config.yaml

# Set project, entity and name for sweep
program: ~/ultimate-utils/ultimate-utils-proj-src/uutils/wandb_uu/sweeps_common.py
project: playground
entity: brando
name: debug-logging-to-wandb-plataform-test  # sweep name. Note this replaces the wandb group for organizing runs
description: debug-not-logging-to-wandb-plataform-test # Added from the other configuration file

# Define metric to optimize
metric:
  name: train_loss
  goal: minimize

# Choose method for sweep
method: random

# Define hyperparameters to sweep over
#parameters:
optimizer: nadam
scheduler: cosine
lr: 0.0001
batch_size: 32
num_its: 2

# Specify a maximum number of runs in a sweep (I'm using this as number of counts)
run_cap: 1

# do real sweep or debug with HF trainer & set wandb.init correct (note, mode cannot be read from wand.config since wand.init has to be called first)
# opt1 ("none", "disabled") yes == debug no wandb
#report_to: none # turn off all HF trainer's wandb tracking, including with wandb in HF TrainingArguments.
#mode: disabled # turn off tracking in wandb via wandb.init(mode)

