# wandb-sweep-config.yaml

# Set project, entity and name for sweep
program: ~/ultimate-utils/tutorials_for_myself/my_wandb_uu/my_wandb_sweeps_uu/sweep_in_python_yaml_config/sweep_config.yaml
project: playground
entity: brando
name: my-ultimate-sweep

# Define metric to optimize
metric:
  name: train_loss
  goal: minimize

# Choose method for sweep
method: random

# Define hyperparameters to sweep over
parameters:
  optimizer:
    values: # Values to sweep over for optimizer hyperparameter
      - adam
      - adafactor
  scheduler:
    values: # Values to sweep over for scheduler hyperparameter
      - cosine
      - none
  lr:
    distribution: log_uniform_values # Distribution for lr hyperparameter
    min: 0.01 # Minimum value for lr hyperparameter
    max: 0.9 # Maximum value for lr hyperparameter
  batch_size:
    distribution: q_log_uniform_values # Distribution for batch_size hyperparameter
    q: 8 # Number of quantization levels for batch_size hyperparameter
    min: 32 # Minimum value for batch_size hyperparameter
    max: 256 # Maximum value for batch_size hyperparameter
  num_its:
    value: 5 # Fixed value for num_its hyperparameter
