FROM ubuntu

RUN apt-get update
RUN apt-get install -y vim

# docker run --rm -v /Users/brandomiranda/Documents/MIT/MEng/hbf_tensorflow_code/docker_files/volumes_test/folder:/folder -ti ubuntu bash
VOLUME /Users/brandomiranda/Documents/MIT/MEng/hbf_tensorflow_code/docker_files/volumes_test/folder/ /folder
