version: "3.2"
# Common Docker Compose File (Shared Services Between Local, Staging, and Production)
services:
  db: # Primary Database
    container_name: curis_db
    restart: unless-stopped
    image: postgres:12.0
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - main
  sp: # SAML Service Provider
    container_name: curis_sp
    restart: unless-stopped
    build:
      context: ./shibboleth-sp
      dockerfile: Dockerfile
    networks:
      - main
  frontend: # React Frontend
    container_name: curis_frontend
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: build.Dockerfile
    networks:
      - main
  api: # Django Backend
    container_name: curis_api
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    entrypoint: ./docker-entrypoint.sh ./docker-gunicorn.sh
    environment:
      - DJANGO_SETTINGS_MODULE=curis.settings
    volumes:
      - api-media:/curis_media
    networks:
      - main
    depends_on:
      - db

volumes:
  db-data:
  api-media:

networks:
  main: