version: "3.2"

services:
  sp:
    build:
      args:
        HOST: ${HOSTNAME_LOCAL}
        IDP: https://${HOSTNAME_LOCAL}:4443/idp/simplesamlphp
      dockerfile: local.Dockerfile
    ports:
      - "80:80"
      - "443:443"
  idp: # SAML Identity Provider
    container_name: curis_idp
    build:
      context: ./simplesamlphp-idp
      dockerfile: Dockerfile
      args:
        HOST: ${HOSTNAME_LOCAL}
    ports:
      - "8080:80"
      - "4443:443"
  frontend:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public
    environment:
      - NODE_ENV=development
      - BASE_URL=https://${HOSTNAME_LOCAL}/api
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
  api:
    entrypoint: ./docker-entrypoint.sh ./docker-runserver.sh
    environment:
      - DJANGO_ENV_MODULE=curis.settings.docker_local
      - HOSTNAME=${HOSTNAME_LOCAL}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./backend:/code